### ISSUE TITLE
Not working with root javascript references 

### ISSUE THREAD

**Issue by Mimetis** [OfficeDev/microsoft-teams-tunnelrelay#10]
Hi Team;

I tried to use the Tunnel relay with an **Angular 5** application, because of the sub folder of the tunnel redirection.   
For instance, here is my config:
`http://localhost:4200` redirect to `https://msteams.servicebus.windows.net/MY-MACHINE-NAME/`  

As expected, it works for the root homepage, but this homepage is referencing javascript files:

``` html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Teamsng5</title>
  <base href="/">

   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body class="theme-light">
  <div class="surface">
    <div class="panel">
      <app-root></app-root>
    </div>
  </div>


 <script src="https://statics.teams.microsoft.com/sdk/v1.0/js/MicrosoftTeams.js"></script>
<script type="text/javascript" src="inline.bundle.js"></script>
<script type="text/javascript" src="polyfills.bundle.js"></script>
<script type="text/javascript" src="styles.bundle.js"></script>
<script type="text/javascript" src="vendor.bundle.js"></script>
<script type="text/javascript" src="main.bundle.js"></script>

</body>

</html>
```

What happened is that the url invoked for each script is something like `https://msteams.servicebus.windows.net/inline.bundle.js`  

And obviously it doesn't work at all.

Do you have any idea on how to proceed ?

Thx

**Comment by RamjotSingh** [comment]
You need to make your js reference relative to root. This is the kind of issue that usually developers hit when their code is not deployed to root folder. Thought this might not be exactly the case for you but you should try looking if following link helps you

https://stackoverflow.com/questions/21670650/what-is-the-difference-between-relative-and-absolute-paths-in-aspnet-mvc

In short you probably need to make your paths relative to root of site and not absolute.

**Comment by Mimetis** [comment]
You're right,
Actually, a **Angular 5** use the this base path, to make everything works.

So that's why, you have to put this in your `index.html` file:

```
  <base href="/">
```

And it does not work with the Tunnel relay.

So, I will continue to use **ngrok** instead !

Thx

Seb
