### ISSUE TITLE
Subscriptions list is empty

### ISSUE THREAD

**Issue by mwiedemeyer** [OfficeDev/microsoft-teams-tunnelrelay#11]
My issue is, that after successful login to my Azure Account the "SelectServiceBus" dialog is shown, but the subscriptions list is empty.
[This line](https://github.com/OfficeDev/microsoft-teams-tunnelrelay/blob/cc0617dfce831391315d5df71600805b88a1c746/TunnelRelay/UIPages/SelectServiceBus.xaml.cs#L111) returns an empty list and I have absolutely no idea why.
I've updated the code add a [tenant selection box](https://github.com/mwiedemeyer/microsoft-teams-tunnelrelay/tree/update-rm). That one shows all my tenants correctly, but it doesn't matter which one I select, the subscriptions list remains empty and returns no results.

Any ideas?

**Comment by RamjotSingh** [comment]
I will take a look at this. Token reacquire might be required with correct tenant setting (instead of login.microsoftonline.com/common to login.microsoftonline.com/<TenantId>).

**Comment by RamjotSingh** [comment]
I did a brief hack code and seems like rotating tokens does solve the issue of fetching subscriptions. The issue seems to be hit when you are granted access to a subscription which is not a part of your core tenant. I can look into how to bake it into core (because resource access will have to be done with respective tokens as well).

**Comment by mwiedemeyer** [comment]
Thank you very much!

**Comment by RamjotSingh** [comment]
I have a PR open to fix this - https://github.com/OfficeDev/microsoft-teams-tunnelrelay/pull/12

You can try using my private branch and see if it solves your issue.

**Comment by RamjotSingh** [comment]
PR has been merged. Closing this issue.

**Comment by dgordoncal** [comment]
Is a new build being released soon with this fix?  I am seeing this issue and have tried logging in with multiple different accounts with various direct and indirect access to azure subscriptions but it's always blank.
