### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by casieo** [OfficeDev/microsoft-teams-tunnelrelay#13]
Hi!  I'm hoping to use this at least as a short term workaround as a way to sideload a bot into teams for which we can't have a public url.  Question: is there a way to start TunnelRelay automatically with exported settings?  So that I could deploy it as part of a service, and it would automatically start and be listening/redirecting?

Thanks.

**Comment by RamjotSingh** [comment]
The way does not exist today but it should be fairly easy to build.
Refer to function ```BtnImportSettings_Click``` in 

https://github.com/OfficeDev/microsoft-teams-tunnelrelay/blob/master/TunnelRelay/UIPages/LoginToAzure.xaml.cs

The main code you are looking for is 

```ApplicationData.ImportSettings(File.ReadAllText(openFileDialog.FileName));```

This will populate the required settings in memory and then on application close save those settings as well (you can obvious choose to always do this however it is not required).

**Comment by casieschuller** [comment]
Thank you for the specific pointers!  I got it done.  :)
