### ISSUE TITLE
Select Subscription

### ISSUE THREAD

**Issue by mharnetiaux** [OfficeDev/microsoft-teams-tunnelrelay#29]
Hello,

I'm probably being a total newbie, but I cant seem to make a selection. I type the number associated with the subscription and press enter, but nothing happens. What am doing wrong? Thanks for your time.

**Comment by RamjotSingh** [comment]
Can you share screenshot? Also which OS are you using?

**Comment by mharnetiaux** [comment]
Mac

**Comment by RamjotSingh** [comment]
And if you type 1, 2, 3 or 4 and press enter nothing happens?

**Comment by mharnetiaux** [comment]
Yeah nothing happens.

**Comment by RamjotSingh** [comment]
I will try to debug through. Might be a bit slow since I do not own a mac :). If you have a windows machine and could try there it would be helpful. The application settings file it creates is portable so you can copy it over to Mac.

**Comment by mharnetiaux** [comment]
Awesome, thanks. Unfortunately I don't have a windows machine.

**Comment by mharnetiaux** [comment]
P.s. I also noticed this issue.
<img width="884" alt="Screen Shot 2020-11-03 at 10 33 59 AM" src="https://user-images.githubusercontent.com/5769834/98026589-354b8480-1dc0-11eb-8c0b-6482f9e4173f.png">

**Comment by mharnetiaux** [comment]
Hey so I was able to get it working by installing visual studio for mac. I'm still confused how to see the GUI? I can only seem to run in the console.

**Comment by mharnetiaux** [comment]
I'm also getting these errors when I visit the redirect url
<img width="1281" alt="Screen Shot 2020-11-05 at 9 59 05 AM" src="https://user-images.githubusercontent.com/5769834/98278526-95236600-1f4d-11eb-91db-1dd3cc3a5597.png">

**Comment by RamjotSingh** [comment]
GUI only works in Windows. Linux and MacOS only have Command line variant.

**Comment by mharnetiaux** [comment]
Thanks for the responses :). Real quick q - have you used or have any good documentation working with localhost:port ?

**Comment by RamjotSingh** [comment]
I am not sure I understand your question. Localhost:port for backend (the service u r fronting) is already allowed.

**Comment by mharnetiaux** [comment]
Oh i'm hitting the url https://plgrelay.servicebus.windows.net/content and can't seem to load my app. Seems maybe like a proxy issue? The last image I posted is the error I see in the chrome console. Basically i'm just getting the html doc, but my js files return the following response - 
![Uploading Screen Shot 2020-11-05 at 10.40.05 AM.png…]()
