### ISSUE TITLE
Please make hybrid connection name configurable

### ISSUE THREAD

**Issue by v-kydela** [OfficeDev/microsoft-teams-tunnelrelay#30]
It would be nice to use the same hybrid connection and therefore the same URL on different machines. This is currently difficult because Tunnel Relay bases the name of the hybrid connection on the name of the machine. Please allow us to configure this.

**Comment by RamjotSingh** [comment]
You actually can do this. appsettings.json has the hybrid connection name. You can change the name there. TunnelRelay will honor it.

**Comment by v-kydela** [comment]
@RamjotSingh - I tried that and it wouldn't connect. Do I need to create a hybrid connection in Azure manually in that case?

**Comment by RamjotSingh** [comment]
Yes the connection needs to exist. You can create one from portal. If you want to keep reusing the same config. One option would be to unselect encryption option during initial configuration phase (where you select relay to use). Finish the setup and copy and reuse the appSettings.json file. However if you want to use a completely custom name then you need to manually create from portal.

**Comment by v-kydela** [comment]
@RamjotSingh - Thank you for the advice. It sounds like the feature I requested would be useful. Tunnel Relay creates a hybrid connection automatically using its default name, so it should be able to do the same with a user-configured name.

Would you please consider reopening this issue?
