### ISSUE TITLE
Package as a .NET tool

### ISSUE THREAD

**Issue by drub0y** [OfficeDev/microsoft-teams-tunnelrelay#31]
Would like to suggest making the CLI version installable as a [.NET tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).

**Comment by RamjotSingh** [comment]
Thanks, will take a look!

**Comment by jongio** [comment]
Update on this?

**Comment by RamjotSingh** [comment]
Haven't gotten around to do this. I am thinking of doing it .Net 6 upgrade once it is out.

**Comment by RamjotSingh** [comment]
I looked a bit deeper and this does not sound like the right choice. TunnelRelay uses sticky configs, which means u can have it across different folders connected to different relays. Packaging as a .Net tool takes that away. With Net3.1 I had enabled publish as single file which instead works better as it offers portability.
