### ISSUE TITLE
TunnelRelay unable to connect to remote server

### ISSUE THREAD

**Issue by DanielLevy0705** [OfficeDev/microsoft-teams-tunnelrelay#46]
I'm using the latest version of TunnelRelay for Linux, on a CentOS7 environment.
Upon running the TunnelRelay.Linux.Console script I'm getting the following error - 
![image](https://github.com/OfficeDev/microsoft-teams-tunnelrelay/assets/45950605/54adf036-0c95-4bdc-9be6-d6190881d6e0)
is there anything that could've caused this issue?

**Comment by RamjotSingh** [comment]
Ensure that service bus exists and so does the hybrid connection. Additionally, ensure the keys havent changed. You can try deleting the appSettings.json file and setup the connection again.

**Comment by DanielLevy0705** [comment]
Thanks @RamjotSingh , I'll check.
Is there any chance that it's related also to some proxy/firewall definitions?
do you know about any specific domains that I should allow a connection to?

**Comment by RamjotSingh** [comment]
It might be, if your firewall is blocking access, the connection woudl fail. You can allow the domain of the Relay at the very least and try.

**Comment by DanielLevy0705** [comment]
@RamjotSingh we've tried opening public access to the relay service, and also deleted appSettings, and went through the setup again but still couldn't connect.
any other ideas why would it happen.

**Comment by RamjotSingh** [comment]
Can you try connecting from an environment which is not behind firewall and see if it works? The error you are seeing means application can't connect to Azure. 

You can also refer to https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-safelist-urls?tabs=public-cloud

**Comment by DanielLevy0705** [comment]
would try it.
Thanks!
is there any option for getting more information regarding the issue from running the script? maybe run it on debug mode somehow to get more logs?
